[package]
name = "autoscape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autopilot = "0.4.0"
device_query = "1.1.1"
dialoguer = "0.10.2"
rodio = "0.16.0"
scrap = "0.5.0"
